/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#1a1c1c',
        'tertiary-fixed': '#ffdbcd',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed': '#dde4e2',
        secondary: '#59605f',
        'primary-container': '#005bc4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#360f00',
        tertiary: '#7e2e00',
        primary: '#004496',
        'outline-variant': '#c2c6d5',
        'on-primary-fixed-variant': '#004395',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed-variant': '#414847',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a43f01',
        'on-primary': '#ffffff',
        'surface-container': '#eeeeed',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e8e8e7',
        'on-tertiary-container': '#ffd0bc',
        'tertiary-fixed-dim': '#ffb596',
        'surface-variant': '#e2e2e2',
        'on-primary-container': '#cbdaff',
        'on-surface-variant': '#424753',
        outline: '#727784',
        'inverse-primary': '#adc6ff',
        'surface-tint': '#005ac2',
        'on-secondary-container': '#5f6665',
        'on-error-container': '#93000a',
        background: '#f9f9f8',
        'surface-container-low': '#f3f4f3',
        surface: '#f9f9f8',
        'inverse-surface': '#2f3130',
        'secondary-fixed-dim': '#c1c8c7',
        'primary-fixed': '#d8e2ff',
        'secondary-container': '#dde4e2',
        error: '#ba1a1a',
        'on-primary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#7c2e00',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f1f1f0',
        'surface-dim': '#dadad9',
        'surface-bright': '#f9f9f8',
        'on-surface': '#1a1c1c',
        'on-secondary-fixed': '#161d1c',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
